    # .github/workflows/ci_cd.yml

    name: CI/CD Pipeline for Tomato Disease Classifier

    on:
      push:
        branches:
          - main
          - develop
      pull_request:
        branches:
          - main
          - develop

    jobs:
      build_and_test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11' # Changed from 3.9 to 3.11 for broader compatibility with 1.6.1
            # You could also try '3.10' or '3.12'
            # Note: 3.13.1 might still have sparse wheel availability for some packages

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r app/requirements.txt
            pip install pytest pyyaml scikit-learn matplotlib seaborn tqdm

        - name: Run unit tests
          run: |
            pytest tests/test_data_preprocessing.py

        - name: Build Docker image (optional, for verification)
          run: docker build -t tomato-disease-classifier-app -f app/Dockerfile .
    